### ISSUE TITLE
ver 3.0.0 problem

### ISSUE THREAD

**Issue by chybbud** [msasanmh/SecureDNSClient#162]
hi i use ver 2.9.2 using 5 server sdns://..... and working all on ipleak.net

after update to 3.0.0 when i check on ipleak.net it just using 1 server the best ping only, how to use 5 server dns at same time?

**Comment by msasanmh** [comment]
> hi i use ver 2.9.2 using 5 server sdns://..... and working all on ipleak.net
> 
> after update to 3.0.0 when i check on ipleak.net it just using 1 server the best ping only, how to use 5 server dns at same time?

I think you misunderstood the meaning of using n servers at the same time.

You're using 5 servers in parallel. It means the app sends your request to all 5 servers at the same time. 
One of the servers sends the answer sooner than others, so the app will cancel the others. 
It's gonna keep the answer until Time-To-Live runs out.

By this way, it can get your answer as fast as possible. 

You can't use more than one answer for one question. 

The only thing has changed since version 3, is the app is doing its job better and faster than before.
