### ISSUE TITLE
How to change the default scanning website?

### ISSUE THREAD

**Issue by Typhonling** [msasanmh/SecureDNSClient#209]
I set up a DOQ server which should work, but it doesn't because it gets offline results when scanning.

In DNS Scanner, it says "Getting Response For: youtube.com".
DNS lookup results for youtube in my area may be blocked or polluted.

How can I change this default value? In Settings, the Check category has an option called "A DNS based blocked website to check", But changing it doesn't seem to do anything.

**Comment by msasanmh** [comment]
> I set up a DOQ server which should work, but it doesn't because it gets offline results when scanning.
> 
> In DNS Scanner, it says "Getting Response For: youtube.com".
> DNS lookup results for youtube in my area may be blocked or polluted.
> 
> How can I change this default value? In Settings, the Check category has an option called "A DNS based blocked website to check", But changing it doesn't seem to do anything.
> 

DoQ and ODoH are not supported yet. They require .NET 8, that's why I'm writing SDC Plus. The current app is using .NET 6 to support Windows 7.

BTW, you can change the default scanning website by changing "A DNS based blocked website to check". If you see something about YouTube in the log, it's checking whether YouTube is restricted by the DNS you provide or not.

**Comment by Typhonling** [comment]
Thank you for your reply, I will continue to use DOH3 until the new features arrive.
