### ISSUE TITLE
Random Servers

### ISSUE THREAD

**Issue by noyzen** [msasanmh/SecureDNSClient#32]
Hi and again, thanks for this program. I use all day :)
But,

Sometimes when I search for servers I find fast and good DNS servers, but each time I open program again I have to wait for server search and it find another servers this time...

Is there a way to see or save good servers and use it again?
Can you send me list of servers so I can add them into custom servers and keep best ones and avoid waiting for search each time?

Regards.

**Comment by msasanmh** [comment]
> Hi and again, thanks for this program. I use all day :)
> But,
> 
> Sometimes when I search for servers I find fast and good DNS servers, but each time I open program again I have to wait for server search and it find another servers this time...
> 
> Is there a way to see or save good servers and use it again?
> Can you send me list of servers so I can add them into custom servers and keep best ones and avoid waiting for search each time?
> 
> Regards.

Part 1, if it finds different servers each time it means they're trying to block all DoH servers.

Part 2, there's no such thing as good servers here, you can't use some specific public servers all the time, otherwise I wouldn't put all those servers in the app.

Part 3, again there's no best ones, also if I make built-in servers visible they would be block in a blink.

Suggestions:

1. You can try connect to cloudflare in the connect tab, it doesn't require servers check. (You need to see if it's compatible with you ISP)

2. Decrease check timeout in settings so you can check servers faster.

3. You don't need to wait until the check is done. Cancel the check operation if you got a few working servers. 

_I'm sure you understand the situation_
